name: Changelog
on:
  pull_request:
    types:
      - closed
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.ACC_TOK }}
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACC_TOK }}
        with:
          source_file: '/github/workspace/CHANGELOG.md'
          destination_repo: 'PS00161093/leetcode-solutions'
          user_email: 'ps.arraha@gmail.com'
          user_name: 'PS00161093'
          commit_message: 'Updated change log'
